packages:
  - packages/*
  - scripts/go/*
  - scripts/send/*
  - scripts/aws/*
  - scripts/interop/*
  - functions/*

allowBuilds:
  esbuild: true
  unrs-resolver: true

catalog:
  '@aws-sdk/client-athena': '^3.1034.0'
  '@aws-sdk/client-bedrock-runtime': '^3.1034.0'
  '@aws-sdk/client-cloudformation': '^3.1034.0'
  '@aws-sdk/client-cloudwatch': '^3.1034.0'
  '@aws-sdk/client-cloudwatch-logs': '^3.1034.0'
  '@aws-sdk/client-dynamodb': '^3.1034.0'
  '@aws-sdk/client-ec2': '^3.1034.0'
  '@aws-sdk/client-ecs': '^3.1034.0'
  '@aws-sdk/client-eventbridge': '^3.1034.0'
  '@aws-sdk/client-kinesis': '^3.1034.0'
  '@aws-sdk/client-kms': '^3.1034.0'
  '@aws-sdk/client-lambda': '^3.1034.0'
  '@aws-sdk/client-s3': '^3.1034.0'
  '@aws-sdk/client-sqs': '^3.1034.0'
  '@aws-sdk/client-ssm': '^3.1034.0'
  '@aws-sdk/client-sts': '^3.1034.0'
  '@aws-sdk/credential-provider-ini': '^3.972.33'
  '@aws-sdk/util-dynamodb': '^3.996.2'
  '@eslint/js': '^10.0.1'
  '@slack/web-api': '^7.15.1'
  '@types/aws-lambda': '^8.10.161'
  '@types/luxon': '^3.7.1'
  '@types/node': '^24.12.2'
  '@typescript-eslint/eslint-plugin': '^8.59.0'
  '@typescript-eslint/parser': '^8.59.0'
  'commander': '^14.0.3'
  'esbuild': '^0.28.0'
  'eslint': '^10.2.1'
  'eslint-config-prettier': '^10.1.8'
  'eslint-plugin-prettier': '^5.5.5'
  'eslint-plugin-security': '^4.0.0'
  'fuse.js': '^7.3.0'
  'glob': '^13.0.6'
  'globals': '^17.5.0'
  'knip': '^6.6.1'
  'license-checker-rseidelsohn': '^4.4.2'
  'luxon': '^3.7.2'
  'prettier': '3.8.3'
  'tsx': '^4.21.0'
  'typescript': '^6.0.3'
  'typescript-eslint': '^8.59.0'
  'yaml': '^2.8.3'

catalogMode: strict
