import type { AlarmAnalysisDto } from '@go-automation/go-watchtower-client';

const NOW = '2026-01-01T00:00:00.000Z';

export function alarmAnalysisFixture(partial: Partial<AlarmAnalysisDto>): AlarmAnalysisDto {
  return {
    alarm: { id: 'alarm-id', name: 'alarm-name' },
    alarmId: 'alarm-id',
    analysisDate: NOW,
    analysisType: 'ANALYZABLE',
    avgMttaMs: null,
    avgMttfMs: null,
    avgMttrMs: null,
    conclusionNotes: null,
    createdAt: NOW,
    createdBy: { email: 'operator@example.invalid', id: 'operator-id', name: 'Operator' },
    createdById: 'operator-id',
    downstreams: [],
    environment: { id: 'environment-id', name: 'production' },
    environmentId: 'environment-id',
    errorDetails: null,
    finalActions: [],
    firstAlarmAt: NOW,
    id: 'analysis-id',
    ignoreDetails: null,
    ignoreReason: null,
    ignoreReasonCode: null,
    isOnCall: true,
    lastAlarmAt: NOW,
    linkedEventsCount: 1,
    links: [],
    occurrences: 1,
    operator: { email: 'operator@example.invalid', id: 'operator-id', name: 'Operator' },
    operatorId: 'operator-id',
    product: { id: 'product-id', name: 'product' },
    productId: 'product-id',
    qualityScore: null,
    resources: [],
    runbook: null,
    runbookId: null,
    scoredAt: null,
    status: 'COMPLETED',
    trackingIds: [],
    updatedAt: NOW,
    updatedBy: null,
    updatedById: null,
    validationScore: null,
    ...partial,
  };
}
