/**
 * Notification status
 */
export enum SENDNotificationStatus {
  IN_VALIDATION = 'IN_VALIDATION',
  ACCEPTED = 'ACCEPTED',
  REFUSED = 'REFUSED',
  DELIVERING = 'DELIVERING',
  DELIVERED = 'DELIVERED',
  VIEWED = 'VIEWED',
  EFFECTIVE_DATE = 'EFFECTIVE_DATE',
  PAID = 'PAID',
  UNREACHABLE = 'UNREACHABLE',
  CANCELLED = 'CANCELLED',
}
